name: CI

on:
  push:
    branches: [ master, feature-*, hotfix-*, release-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SemVer
        with:
          repo-path: ${{ github.workspace }}
        id: semver
        uses: luanlmd/semver-composite-action@v16

      - name: Test SemVer
        run: |
          echo "Version: ${{ steps.semver.outputs.version }}"

      - name: Docker Build
        run: docker build . -f docker/prod.Dockerfile -t luanlmd/docker-rust-seed:v${{ github.run_number }}

      - name: Docker Login
        run: docker login -u luanlmd -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker Push
        run: docker push luanlmd/docker-rust-seed:v${{ github.run_number }}

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Update Cloud Run Service
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          region: southamerica-east1
          service: 'rust'
          image: 'luanlmd/docker-rust-seed:v${{ github.run_number }}'
